<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LOGIN Panel</name>
   <tag></tag>
   <elementGuidId>7cd8e797-cce9-4ceb-9780-89028d9694e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logInPanelHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logInPanelHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5513be6c-65fa-48fd-9bed-22cbc99b0d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logInPanelHeading</value>
      <webElementGuid>23917f05-e0a5-43b8-a133-107cf8e4982d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN Panel</value>
      <webElementGuid>fae9fdca-c4cb-480e-9731-a7d9cbc0453e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logInPanelHeading&quot;)</value>
      <webElementGuid>aeba7245-487d-4e32-89ab-aac0f536b6e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='logInPanelHeading']</value>
      <webElementGuid>04aafc88-1be3-472f-88d7-966a25f66233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmLogin']/div</value>
      <webElementGuid>031ff285-5508-48f5-97e5-dd232cd8e517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='( Username : Admin | Password : admin123 )'])[1]/following::div[6]</value>
      <webElementGuid>a3a96001-ad3a-49ef-b72e-89a03b8187f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::div[1]</value>
      <webElementGuid>ba3cf43a-be48-4d3a-b615-b920d3771344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::div[2]</value>
      <webElementGuid>f1369f20-d40a-4744-8429-daf6799242c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN Panel']/parent::*</value>
      <webElementGuid>768683f3-042d-4dcd-9cd5-bb2876d60c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>18ffdc15-75ab-41ab-aed8-3805c981eb28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'logInPanelHeading' and (text() = 'LOGIN Panel' or . = 'LOGIN Panel')]</value>
      <webElementGuid>9c37e48d-6e82-4b22-9ef2-6caac71aa014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
